import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/default/navbar/Navbar";

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
const openSans = Open_Sans({
  variable: "--font-opensans",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full font-sans antialiased",
          openSans.className,
          inter.className
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar></Navbar>
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
